language: swift
osx_image: xcode11.4
cache:
    bundler: true
    directories:
     - /home/travis/.rvm/
before_install:
  - bundle check || bundle install --path vendor/bundle --without development
  - bundle update 
git:
  depth: 1

stages:
  - name: test

branches:
  only:
  - development

jobs:
  include:
    - stage: test
      name: Run tests
      osx_image: xcode11.4
      script: bundle exec fastlane test

    - stage: test
      name: Run Validations (SwiftLint)
      osx_image: xcode11.4
      install: Scripts/install_swiftlint.sh
      script: Scripts/validate.sh